### ISSUE TITLE
编译信息抹除与字符串混淆时出错，这是什么问题，请问你的go环境是多少版的？

### ISSUE THREAD

**Issue by lx1xl** [NyDubh3/CuiRi#10]
[INFO] 已生成木马，正在进行编译信息抹除与字符串混淆...
[Fatal] exit status 2%!(EXTRA string=2022/05/10 11:14:02 开始混淆
2022/05/10 11:14:02 文件结构:PE
2022/05/10 11:14:02 混淆 BuildId
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x1ed77e]

goroutine 1 [running]:
github.com/goretk/gore/gosym.(*Table).GetGo12(...)
        /home/runner/work/go-strip-source/go-strip-source/gosym/symtab.go:485
github.com/goretk/gore.(*GoFile).GetGoRoot(0xc00001d040, 0xc000006018, 0xc00005bf28)
        /home/runner/work/go-strip-source/go-strip-source/file.go:195 +0x3e
main.main()
        /home/runner/work/go-strip-source/go-strip-source/testM/main.go:48 +0x2d0
)

**Comment by BloodGhostlg** [comment]
你的解决了吗

**Comment by pighhh** [comment]
我的也是这样子的报错，有什么解决办法吗

**Comment by ghost** [comment]
使用golang 1.16.4版本可以
