### ISSUE TITLE
cs要用什么版本，我的是4.0生成出来的payload，用工具报错

### ISSUE THREAD

**Issue by 2440012586** [NyDubh3/CuiRi#11]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0xc6d77e]

goroutine 1 [running]:
github.com/goretk/gore/gosym.(*Table).GetGo12(...)
        /home/runner/work/go-strip-source/go-strip-source/gosym/symtab.go:485
github.com/goretk/gore.(*GoFile).GetGoRoot(0xc000192000, 0xc000006018, 0xc0002fdf28)
        /home/runner/work/go-strip-source/go-strip-source/file.go:195 +0x3e
main.main()
        /home/runner/work/go-strip-source/go-strip-source/testM/main.go:48 +0x2d0

**Comment by yanabcd** [comment]
是不是go版本问题

**Comment by ghost** [comment]
使用golang 1.16.4版本可以

**Comment by XiaoanHi** [comment]
确实，我使用golang 1.20.4也不行，切换到 golang 1.14.15 就可以正常生成了
